// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-eJqSBptU_L6ovkYfVetXOZsoeAB9Nd0',
    appId: '1:983114781361:web:76f86a968d53a22609c890',
    messagingSenderId: '983114781361',
    projectId: 'stay-safe-route',
    authDomain: 'stay-safe-route.firebaseapp.com',
    storageBucket: 'stay-safe-route.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJNModUDovOEw7cVdzb056Wtb1_60DnpU',
    appId: '1:983114781361:android:15fe68c7e5411f5009c890',
    messagingSenderId: '983114781361',
    projectId: 'stay-safe-route',
    storageBucket: 'stay-safe-route.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1OYywiDQYTDD-DlsNIDqVfhQPULs1LgI',
    appId: '1:983114781361:ios:77de5143249efb2909c890',
    messagingSenderId: '983114781361',
    projectId: 'stay-safe-route',
    storageBucket: 'stay-safe-route.firebasestorage.app',
    iosBundleId: 'com.example.ssrParentApp',
  );

}